"""full schema

Revision ID: 0816a3f13942
Revises: b2bb4cc79060
Create Date: 2025-12-02 00:27:45.580208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0816a3f13942'
down_revision: Union[str, Sequence[str], None] = 'b2bb4cc79060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('legal_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(), nullable=True))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address_line2')
    op.drop_column('organizations', 'address_line1')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'legal_name')
    # ### end Alembic commands ###
